force-app/main/default/objects/Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomerAppointmentController.cls
//This Controller will Query the information in the custom Object:
//Appointment__c; The Status__c
public class CustomerAppointmentController {
	/**Need to write method that will query the Appointment__c Object
	then pull the picklist value of the Status__c field to inform
	the cusomer on the status of the appointment they requested**/
    
    @AuraEnabled
    public static List<Appointment__c> getAppointmentStatus(){
        List<Appointment__c> appointments = [SELECT Name FROM Appointment__c];
        /**I still need the following pieces of information: 
         * Residence.Office_Location_c.Full_address_c, Doctor_r.Name,
           Start_time_c, End_time_c, Status_c, Doctor_message_c**/
        return appointments;
    }
}